let schedule = [
        //Week 17
        new Game("TEN", "DAL", null, null),
        new Game("ATL", "ARI", null, null),
        new Game("DET", "CHI", null, null),
        new Game("HOU", "JAC", null, null),
        new Game("KC", "DEN", null, null),
        new Game("NE", "MIA", null, null),
        new Game("NYG", "IND", null, null),
        new Game("PHI", "NO", null, null),
        new Game("TB", "CAR", null, null),
        new Game("WAS", "CLE", null, null),
        new Game("LV", "SF", null, null),
        new Game("SEA", "NYJ", null, null),
        new Game("GB", "MIN", null, null),
        new Game("LAC", "LAR", null, null),
        new Game("BAL", "PIT", null, null),
        new Game("CIN", "BUF", null, null),

        //Week 18
        new Game("ATL", "TB", null, null),
        new Game("BUF", "NE", null, null),
        new Game("CHI", "MIN", null, null),
        new Game("CIN", "BAL", null, null),
        new Game("GB", "DET", null, null),
        new Game("IND", "HOU", null, null),
        new Game("JAC", "TEN", null, null),
        new Game("MIA", "NYJ", null, null),
        new Game("NO", "CAR", null, null),
        new Game("PHI", "NYG", null, null),
        new Game("PIT", "CLE", null, null),
        new Game("WAS", "DAL", null, null),
        new Game("DEN", "LAC", null, null),
        new Game("LV", "KC", null, null),
        new Game("SEA", "LAR", null, null),
        new Game("SF", "ARI", null, null),
];
