let teams = {
    "ARI": new Team("ARI",  "Arizona Cardinals", "NFC", "WEST"),
    "ATL": new Team("ATL",  "Atlanta Falcons", "NFC", "SOUTH"),
    "BAL": new Team("BAL",  "Baltimore Ravens", "AFC", "NORTH"),
    "BUF": new Team("BUF",  "Buffalo Bills", "AFC", "EAST"),
    "CAR": new Team("CAR",  "Carolina Panthers", "NFC", "SOUTH"),
    "CHI": new Team("CHI",  "Chicago Bears", "NFC", "NORTH"),
    "CIN": new Team("CIN",  "Cincinnati Bengals", "AFC", "NORTH"),
    "CLE": new Team("CLE",  "Cleveland Browns", "AFC", "NORTH"),
    "DAL": new Team("DAL",  "Dallas Cowboys", "NFC", "EAST"),
    "DEN": new Team("DEN",  "Denver Broncos", "AFC", "WEST"),
    "DET": new Team("DET",  "Detroit Lions", "NFC", "NORTH"),
    "GB" : new Team("GB", "Green Bay Packers", "NFC", "NORTH"),
    "HOU": new Team("HOU",  "Houston Texans", "AFC", "SOUTH"),
    "IND": new Team("IND",  "Indianapolis Colts", "AFC", "SOUTH"),
    "JAC": new Team("JAC",  "Jacksonville Jaguars", "AFC", "SOUTH"),
    "KC" : new Team("KC", "Kansas City Chiefs", "AFC", "WEST"),
    "LV" : new Team("LV", "Las Vegas Raiders", "AFC", "WEST"),
    "LAC": new Team("LAC",  "Los Angeles Chargers", "AFC", "WEST"),
    "LAR": new Team("LAR",  "Los Angeles Rams", "NFC", "WEST"),
    "MIA": new Team("MIA",  "Miami Dolphins", "AFC", "EAST"),
    "MIN": new Team("MIN",  "Minnesota Vikings", "NFC", "NORTH"),
    "NE" : new Team("NE", "New England Patriots", "AFC", "EAST"),
    "NO" : new Team("NO", "New Orleans Saints", "NFC", "SOUTH"),
    "NYG": new Team("NYG",  "New York Giants", "NFC", "EAST"),
    "NYJ": new Team("NYJ",  "New York Jets", "AFC", "EAST"),
    "PHI": new Team("PHI",  "Philadelphia Eagles", "NFC", "EAST"),
    "PIT": new Team("PIT",  "Pittsburgh Steelers", "AFC", "NORTH"),
    "SF" : new Team("SF", "San Francisco 49ers", "NFC", "WEST"),
    "SEA": new Team("SEA",  "Seattle Seahawks", "NFC", "WEST"),
    "TB" : new Team("TB", "Tampa Bay Buccaneers", "NFC", "SOUTH"),
    "TEN": new Team("TEN",  "Tennessee Titans", "AFC", "SOUTH"),
    "WAS": new Team("WAS",  "Washington Commanders",   "NFC", "EAST"),
};
